spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service

logging:
  level:
    org.mongodb: DEBUG
    org.springframework.data.mongodb: DEBUG